# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

sudo: false
dist: trusty

language: python
python:
  - "3.5"
  - "3.6"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install codecov tox-travis

# command to run tests, e.g. python setup.py test
script:
  - tox

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then codecov -b $TRAVIS_BRANCH; fi

